# @format

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  labels:
    app: web-server
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
      tier: backend

  template:
    metadata:
      labels:
        app: web-server
        tier: backend

    spec:
      volumes:
        - name: dir
          hostPath:
            path: /code
        - name: config
          configMap:
            name: server-config
            items:
              - key: config
                path: site.conf
      containers:
        - name: web-server
          image: nginx
          volumeMounts:
            - name: dir
              mountPath: /CODE
            - name: config
              mountPath: /etc/nginx/conf.d
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web-service
    tier: backend
spec:
  selector:
    app: web-service
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30020
  type: LoadBalancer
