# @format

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-php-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-php
  template:
    metadata:
      labels:
        app: nginx-php
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
          # volumeMounts:
          #   - name: nginx-conf
          #     mountPath: /etc/nginx/conf.d/default.conf
          #     subPath: default.conf
      # volumes:
      #   - name: nginx-conf
      #     configMap:
      #       name: nginx-conf
      #       items:
      #         - key: default.conf
      #           path: default.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    server {
        listen 80;
        # server_name example.com;
        root /var/www/html;
        location / {
            # proxy_pass http://php-container:9000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-php-service
spec:
  selector:
    app: nginx-php
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
    # - name: php
    #   protocol: TCP
    #   port: 9000
    #   targetPort: 9000
  type: NodePort
